apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: masternginx
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: server1
        url: https://kubernetes.default.svc
        image: nginx:1.14.2
      - cluster: server2
        url: hhttps://kubernetes.default.svc
        image: nginx:1.21.1
  template:
    metadata:
      name: '{{cluster}}-nginx'
    spec:
      project: default
      source:
        repoURL: https://github.com/sree52/argo-helm.git
        targetRevision: HEAD
        path: nginxhelm
        helm:
          releaseName: '{{image}}-nginx'
          parameters:
          - name: image
            value: '{{image}}'
      destination:
        server: '{{url}}'
        namespace: default
      syncPolicy:
        automated: {}
